// TASKS constants
export const TASK_ACTIONS = {
  ADD_TASK: "ADD_TASK",
  EDIT_TASK: "EDIT_TASK",
  DELETE_TASK: "DELETE_TASK",
};

export const TASK_SORT_OPTIONS = {
  LATEST: "SORT_LATEST",
  OLDEST: "SORT_OLDEST",
  DUE_DATE: "SORT_DUE_DATE",
  PRIORITY_HIGH: "SORT_PRIORITY_HIGH",
  PRIORITY_LOW: "SORT_PRIORITY_LOW",
};

// PROJECTS constants
export const PROJECT_ACTIONS = {
  ADD_PROJECT: "ADD_PROJECT",
  EDIT_PROJECT: "EDIT_PROJECT",
  DELETE_PROJECT: "DELETE_PROJECT",
};
