export const mockUserData = {
  id: 1,
  uid: "101",
  displayName: "Super User",
  email: "superuser@mail.com",
  password: "awesomeUser123!",
  tasks: [
    {
      id: "TSK-003",
      title: "New Task 3",
      description: "Task 3 description",
      status: "pending",
      startDate: "Feb 19, 2024",
      dueDate: "Mar 02, 2024",
      priority: "High",
      assignedTo: "Design",
    },
    {
      id: "TSK-004",
      title: "New Task 4",
      description: "Task 3 description",
      status: "inProgress",
      startDate: "Feb 18, 2024",
      dueDate: "Mar 01, 2024",
      priority: "Low",
      assignedTo: "Other stuff",
    },
    {
      id: "TSK-005",
      title: "New Task 5",
      description: "Task 3 description",
      status: "pending",
      startDate: "Feb 18, 2024",
      dueDate: "Feb 23, 2024",
      priority: "Low",
      assignedTo: "Unassigned",
    },
    {
      id: "TSK-007",
      title: "New Task 7",
      description: "Task 3 description",
      status: "completed",
      startDate: "Feb 18, 2024",
      dueDate: "Feb 26, 2024",
      priority: "Low",
      assignedTo: "Unassigned",
    },
    {
      id: "TSK-008",
      title: "New Task 8",
      description: "Task 3 description",
      status: "pending",
      startDate: "Feb 18, 2024",
      dueDate: "Feb 21, 2024",
      priority: "High",
      assignedTo: "Unassigned",
    },
  ],
};