export const projectsData = [
  {
    id: 1,
    name: "Design",
    description: "Revamp the company website",
    startDate: "Jan 15 2024",
    endDate: "Feb 15 2024",
    tasks: [

    ],
    progress: 52,
  },
  {
    id: 2,
    name: "Web development",
    description: "Revamp the company website for a better user experience. Them fgbe",
    startDate: "Jan 15 2024",
    endDate: "Apr 7 2024",
    tasks: [],
    progress: 52,
  },
  {
    id: 3,
    name: "Testing",
    description: "Revamp the company website for a better user experience.",
    startDate: "Jan 15 2024",
    endDate: "Apr 7 2024",
    tasks: [],
    progress: 52,
  },
  {
    id: 4,
    name: "Website Redesign",
    description: "Revamp the company website for a better user experience.",
    startDate: "Jan 15 2024",
    endDate: "Apr 7 2024",
    tasks: [],
    progress: 52,
  },
  {
    id: 5,
    name: "Website Redesign",
    description: "Revamp the company website for a better user experience.",
    startDate: "Jan 15 2024",
    endDate: "Apr 7 2024",
    tasks: [],
    progress: 52,
  },
  {
    id: 6,
    name: "Website Redesign",
    description: "Revamp the company website for a better user experience.",
    startDate: "Jan 15 2024",
    endDate: "Apr 7 2024",
    tasks: [],
    progress: 52,
  },
];
