export const projectsData = [
  {
    id: 1,
    title: "Design",
    description: "Revamp the company website",
    creationDate: "Jan 15 2024",
    dueDate: "Feb 15 2024",
    status: "completed",
    priority: "Low",
    tasks: [
      {
        id: "TSK-003",
        title: "New Task 3",
        description: "Task 3 description",
        status: "completed",
        creationDate: "Feb 18, 2024",
        startDate: "Feb 19, 2024",
        dueDate: "Mar 02, 2024",   
        priority: "High",
        assignedTo: "Design",
        projectName: "Design",
      },
      {
        id: "TSK-004",
        title: "New Task 4",
        description: "Task 3 description",
        status: "completed",
        creationDate: "Feb 10, 2024",
        startDate: "Feb 18, 2024",
        dueDate: "Mar 01, 2024",
        priority: "Low",
        assignedTo: "Other stuff",
        projectName: "Design",
      },
      {
        id: "TSK-005",
        title: "New Task 5",
        description: "Task 3 description",
        status: "pending",
        creationDate: "Feb 10, 2024",
        startDate: "Feb 18, 2024",
        dueDate: "Mar 01, 2024",
        priority: "Low",
        assignedTo: "Design",
        projectName: "Design",
      },
      {
        id: "TSK-006",
        title: "New Task 6",
        description: "Task 3 description",
        status: "completed",
        creationDate: "Feb 10, 2024",
        startDate: "Feb 18, 2024",
        dueDate: "Mar 01, 2024",
        priority: "Low",
        assignedTo: "Design",
        projectName: "Design",
      },
    ],
  },
  {
    id: 2,
    title: "Web development",
    description: "",
    creationDate: "Jan 15 2024",
    dueDate: "Apr 7 2024",
    status: "inProgress",
    priority: "High",
    tasks: [],
  },
  {
    id: 3,
    title: "Testing",
    description: "Testing projects for the company",
    creationDate: "Jan 15 2024",
    dueDate: "Apr 7 2024",
    priority: "Low",
    tasks: [
      {
        id: "TSK-012",
        title: "Test Task 4",
        description: "Task description",
        status: "completed",
        creationDate: "Feb 10, 2024",
        startDate: "Feb 18, 2024",
        dueDate: "Mar 01, 2024",
        priority: "Low",
        assignedTo: "Testing",
        projectName: "Testing",
      },
      {
        id: "TSK-013",
        title: "Test Task 5",
        description: "Task description",
        status: "pending",
        creationDate: "Feb 10, 2024",
        startDate: "Feb 18, 2024",
        dueDate: "Mar 01, 2024",
        priority: "Low",
        assignedTo: "Testing",
        projectName: "Testing",
      },
      {
        id: "TSK-014",
        title: "Test Task 6",
        description: "Task description",
        status: "pending",
        creationDate: "Feb 10, 2024",
        startDate: "Feb 18, 2024",
        dueDate: "Mar 01, 2024",
        priority: "Low",
        assignedTo: "Testing",
        projectName: "Testing",
      },
    ],
  },
];
