export const tasksData = [
  {
    id: "TSK-003",
    title: "New Task 3",
    description: "Task 3 description",
    status: "Pending",
    startDate: "Feb 19, 2024",
    dueDate: "Mar 02, 2024",
    priority: "High",
    assignedTo: "Design",
  },
  {
    id: "TSK-004",
    title: "New Task 4",
    description: "Task 3 description",
    status: "In progress",
    startDate: "Feb 18, 2024",
    dueDate: "Mar 01, 2024",
    priority: "Low",
    assignedTo: "Other stuff",
  },
  {
    id: "TSK-005",
    title: "New Task 5",
    description: "Task 3 description",
    status: "Pending",
    startDate: "Feb 18, 2024",
    dueDate: "Feb 23, 2024",
    priority: "Low",
    assignedTo: "Unassigned",
  },
  {
    id: "TSK-007",
    title: "New Task 7",
    description: "Task 3 description",
    status: "Completed",
    startDate: "Feb 18, 2024",
    dueDate: "Feb 26, 2024",
    priority: "Low",
    assignedTo: "Unassigned",
  },
  {
    id: "TSK-008",
    title: "New Task 8",
    description: "Task 3 description",
    status: "Pending",
    startDate: "Feb 18, 2024",
    dueDate: "Feb 21, 2024",
    priority: "High",
    assignedTo: "Unassigned",
  },
  // {
  //   id: "TSK-009",
  //   title: "New Task 9",
  //   description: "Task 3 description",
  //   status: "Pending",
  //   startDate: "Feb 18, 2024",
  //   dueDate: "Feb 23, 2024",
  //   priority: "Medium",
  //   assignedTo: "Unassigned",
  // },
  // {
  //   id: "TSK-006",
  //   title: "New Task 6",
  //   description: "Task 3 description",
  //   status: "Pending",
  //   startDate: "Feb 10, 2024",
  //   dueDate: "Feb 19, 2024",
  //   priority: "Medium",
  //   assignedTo: "Unassigned",
  // },
  // {
  //   id: "TSK-001",
  //   title: "Complete Task feature",
  //   description:
  //     "Create a new task feature in the app. Then add the ability to edit and delete tasks.",
  //   status: "Completed",
  //   startDate: "Feb 10, 2024",
  //   dueDate: "Feb 11, 2024",
  //   priority: "High",
  //   assignedTo: "Web Development",
  // },
  // {
  //   id: "TSK-002",
  //   title: "Finish the UI for the app",
  //   description: "Task 2 description",
  //   status: "Pending",
  //   startDate: "Feb 07, 2024",
  //   dueDate: "Feb 19, 2024",
  //   priority: "Medium",
  //   assignedTo: "Unassigned",
  // },
  // {
  //   id: "TSK-010",
  //   title: "New Task 10",
  //   description: "Task 3 description",
  //   status: "Pending",
  //   startDate: "Feb 17, 2024",
  //   dueDate: "Feb 23, 2024",
  //   priority: "Low",
  //   assignedTo: "Unassigned",
  // },
];
