export const tasksData = [
  {
    id: "TSK-001",
    title: "Complete Task feature",
    description:
      "Create a new task feature in the app. Then add the ability to edit and delete tasks.",
    status: "Completed",
    startDate: "Feb 10, 2024",
    dueDate: "Feb 11, 2024",
    priority: "High",
    projectAssigned: "Web Developement",
  },
  {
    id: "TSK-002",
    title: "Finish the UI for the app",
    description: "Task 2 description",
    status: "Completed",
    startDate: "Feb 07 2024",
    dueDate: "Feb 13, 2024",
    priority: "Medium",
    projectAssigned: "",
  },
  {
    id: "TSK-003",
    title: "New Task 3",
    description: "Task 3 description",
    status: "Pending",
    startDate: "Feb 20, 2024",
    dueDate: "Mar 02, 2024",
    priority: "High",
    projectAssigned: "Design",
  },
  {
    id: "TSK-004",
    title: "New Task 4",
    description: "Task 3 description",
    status: "Pending",
    startDate: "Feb 18, 2024",
    dueDate: "Mar 01, 2024",
    priority: "Low",
    projectAssigned: "Other",
  },
  {
    id: "TSK-005",
    title: "New Task 5",
    description: "Task 3 description",
    status: "In progress",
    startDate: "Feb 18, 2024",
    dueDate: "Feb 23, 2024",
    priority: "Low",
    projectAssigned: "",
  },
];
